// src/app/layout.tsx
import type { Metadata } from "next";
import {  Inter} from "next/font/google";
import "./globals.css";
import { SidebarProvider } from "@/components/ui/sidebar";
import {ClerkProvider} from "@clerk/nextjs";
// import { TRPCProvider } from "@/trpc/client";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const inter = Inter({
  subsets: ["latin"],
});


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
<html lang="en">
      <body className={inter.className}>
        {/* All client-only providers must be inside <body> */}
        <ClerkProvider>
          {/* <TRPCProvider> */}
            <SidebarProvider>
              {children}
            </SidebarProvider>
          {/* </TRPCProvider> */}
        </ClerkProvider>
      </body>
    </html>
    



    
  );
}