// // // // // src/app/layout.tsx
// // // // import "./globals.css";
// // // // import type { Metadata } from "next";
// // // // import {  Inter} from "next/font/google";
// // // // import { SidebarProvider } from "@/components/ui/sidebar";
// // // // import {ClerkProvider} from "@clerk/nextjs";
// // // // import { TRPCProvider } from "@/trpc/client";
// // // // export const metadata: Metadata = {
// // // //   title: "Create Next App",
// // // //   description: "Generated by create next app",
// // // // };

// // // // const inter = Inter({
// // // //   subsets: ["latin"],
// // // // });




// // // // export default function RootLayout({ children }: { children: React.ReactNode }) {
// // // //   return (
// // // //     <html lang="en">
// // // // +      <head />            {/* ← Add this */}
// // // //       <body className={inter.className}>
// // // //         {/* All client-only providers must be inside <body> */}
// // // //         <ClerkProvider>
// // // //           <TRPCProvider>
// // // //             <SidebarProvider>{children}</SidebarProvider>
// // // //           </TRPCProvider>
// // // //         </ClerkProvider>
// // // //       </body>
// // // //     </html>
// // // //   );
// // // // }




// // // // src/app/layout.tsx
// // // import "./globals.css";
// // // import type { Metadata } from "next";
// // // import { Inter } from "next/font/google";
// // // import { SidebarProvider } from "@/components/ui/sidebar";
// // // import { ClerkProvider } from "@clerk/nextjs";
// // // import { TRPCProvider } from "@/trpc/client";

// // // export const metadata: Metadata = {
// // //   title: "Create Next App",
// // //   description: "Generated by create next app",
// // // };

// // // const inter = Inter({ subsets: ["latin"] });

// // // export default function RootLayout({
// // //   children,
// // // }: {
// // //   children: React.ReactNode;
// // // }) {
// // //   return (
// // //     <html lang="en">
// // //       <head />
// // //       <body className={inter.className}>
// // //         <ClerkProvider>
// // //           <TRPCProvider>
// // //             <SidebarProvider>{children}</SidebarProvider>
// // //           </TRPCProvider>
// // //         </ClerkProvider>
// // //       </body>
// // //     </html>
// // //   );
// // // }


// // // src/app/layout.tsx
// // import type { Metadata } from "next";
// // import { Inter } from "next/font/google";
// // import { ClerkProvider } from "@clerk/nextjs";

// // import { TRPCProvider } from "@/trpc/client";
// // import { Toaster } from "@/components/ui/sonner";

// // import "./globals.css";

// // const inter = Inter({ subsets: ["latin"] });

// // export const metadata: Metadata = {
// //   title: "Create Next App",
// //   description: "Generated by create next app",
// // };

// // export default function RootLayout({
// //   children,
// // }: Readonly<{
// //   children: React.ReactNode;
// // }>) {
// //   return (
// //     <ClerkProvider afterSignOutUrl="/">
// //       <html lang="en">
// //         <body
// //           className={inter.className}
// //         >
// //           <TRPCProvider>
// //             <Toaster />
// //             {children}
// //           </TRPCProvider>
// //         </body>
// //       </html>
// //     </ClerkProvider>
// //   );
// // }



// // src/app/layout.tsx

// import "./globals.css"
// import type { Metadata } from "next";
// import { Inter } from "next/font/google";
// import { ClerkProvider } from "@clerk/nextjs";

// import { TRPCProvider } from "@/trpc/client";
// import { Toaster } from "@/components/ui/sonner";


// const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <head />
//       <body className={inter.className}>
//         <ClerkProvider afterSignOutUrl="/">
//           <TRPCProvider>
//             <Toaster />
//             {children}
//           </TRPCProvider>
//         </ClerkProvider>
//       </body>
//     </html>
//   );
  
// }


import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ClerkProvider } from "@clerk/nextjs";

import { TRPCProvider } from "@/trpc/client";
import { Toaster } from "@/components/ui/sonner";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider afterSignOutUrl="/">
      <html lang="en">
        <body
          className={inter.className}
        >
          <TRPCProvider>
            <Toaster />
            {children}
          </TRPCProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}