// src/app/(home)/layout.tsx
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ClerkProvider } from "@clerk/nextjs";
// import "@/app/globals.css";
import { TRPCProvider } from "@/trpc/client";
// import { Toaster } from "@/components/ui/sonner";

import "../globals.css";
import { HomeLayout } from "@/modules/home/ui/layouts/home-layout";
export const inter = Inter({ subsets: ["latin"],variable: "--font-inter"});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <html lang="en" className={inter.variable}>
        <body>
            <ClerkProvider afterSignOutUrl="/">
            <TRPCProvider>
            <HomeLayout>
            {/* <Toaster /> */}
            {children}
            </HomeLayout>
          </TRPCProvider>
          </ClerkProvider>
        </body>
      </html>
    
  );
}